# Generated by Django 2.0.13 on 2019-09-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='article/%Y%m%d'),
        ),
    ]
