# Generated by Django 2.0.13 on 2019-09-14 09:20

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='article/%Y%m%d'),
        ),
    ]
